### ISSUE TITLE
Graphical output not show charts

### ISSUE THREAD

**Issue by roma86** [yandex/yandex-tank#128]
Thank you for software.

Problem:
Tank installed on debian server
cat /etc/debian_version 7.8

"yandex-tank" command works as expected in console. But when i open graphical output from local machine, i can not see charts. 
![Graphical output no charts](https://api.monosnap.com/image/download?id=4RvmJwdmmLH32CvDdRSUerO0dUvSwB)

There are no errors in the chrome console.

I am using http://server.address:8080  for connection of graphical output from my local machine.

Thanks in advance

**Comment by roma86** [comment]
I installed yandex-tank on ubuntu (using virtual box), and have same issue 
![Image of issue]
(https://d1ro8r1rbfn3jf.cloudfront.net/ms_7588/fB0IoCKV2bDhd9BbWuyTJlbwbXgQku/Yandex.Tank%2BOnline%2BTest%2B2015-01-27%2B13-56-22?Expires=1422442731&Signature=gtqJdPRbGcZkinbTys59w6cVNbkhIopTZxzGDNF03pm3RYxSINU4DpuVc57bgO1mcwYeoXlyIee4yVBvT80vAtbTIg-BR5VdFi-cv3~KarwfzfXutn2TnBAATmXLimCOC30NtI30ltTJRVfA0-aB2Atl8goMPgVOUSnfnaH4VGm-GPwP4BpSwaEXdGn8oa6y-Exwgpn5rOxpIMGdUbCwFXd0PjfrHxkhUo6Vtw5GRtKUjab1MLxF--PQFnsf1PMhlq7KPwAf8AbR7JGEpPEtqJPzNsVgmaEFBwH~zDlSH94WbyrKYbCAv3G9Mpz25Dc8K2-uSb9JUpl~5LGVXoVB4w__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by direvius** [comment]
This old online plugin is no longer supported because loadosophia.org stopped to provide javascript for it. We made a new plugin but it is not in debian package yet. You can try the last version from github. The plugin is called OnlineReport (https://github.com/yandex/yandex-tank/tree/master/Tank/Plugins/OnlineReport).

**Comment by roma86** [comment]
thank you for answer

**Comment by direvius** [comment]
https://github.com/yandex-load/yatank-online/
