### ISSUE TITLE
Try BeautifulSoup instead of lxml

### ISSUE THREAD

**Issue by direvius** [yandex/yandex-tank#132]
BeautifulSoup is all-python and lxml is a C extension. So it's easier to deploy BeautifulSoup. But we need to compare them in details before moving from one to another.

**Comment by ei-grad** [comment]
Hey, is that right, that you guys are using lxml only for config parsing?

```
[ ei-grad@yoga-s1 ~/yandex-tank ‹master› ]
→ git grep lxml; git grep etree                 
.travis.yml:  - pip install lxml
data/yandex-tank.spec:Requires:   python-lxml
setup.py:        'lxml',
yandextank/plugins/Monitoring/collector.py:from lxml import etree
yandextank/plugins/Monitoring/collector.py:from lxml import etree
yandextank/plugins/Monitoring/collector.py:        self.tree = etree.parse(config)
yandextank/plugins/Monitoring/collector.py:            tree = etree.parse(filename)
```

Just replace it with builtin xml module. Can't even imagine for what you could need the BeautifulSoup crap...

**Comment by undera** [comment]
Yes, it is intentional. It allows you to paste whole xml config instead of filename and it will work.

**Comment by ei-grad** [comment]
Are you sure want to bring a 50k-lines-of-code library having xpath/xslt implementations just to be able to determine is the variable a file name or a file content?..

**Comment by ei-grad** [comment]
^ is not finished, but I would be grateful if someone could review and test it
