### ISSUE TITLE
Не удается установить phantom

### ISSUE THREAD

**Issue by Hellov** [yandex/yandex-tank#142]
После запуска ```sudo add-apt-repository ppa:yandex-load/main && sudo apt-get update``` получаю ошибки
>W: Failed to fetch http://ppa.launchpad.net/yandex-load/main/ubuntu/dists/utopic/main/binary-amd64/Packages: 404  Not Found
>W: Failed to fetch http://ppa.launchpad.net/yandex-load/main/ubuntu/dists/utopic/main/binary-i386/Packages: 404  Not Found

Ubuntu 14.10

**Comment by nnugumanov** [comment]
https://launchpad.net/~yandex-load/+archive/ubuntu/main/+packages:
   This PPA currently publishes packages for Trusty, Saucy, Raring, Quantal, Precise, and Lucid.

So, currently there are no packages for 14.10. Have you tried Trusty's version? For doing so, you should replace "utopic" with "trusty" in line "deb http://ppa.launchpad.net.. "  in /etc/apt/sources.list

**Comment by direvius** [comment]
I've just copied a precise packages to utopic on launchpad. So it should work now.
