### ISSUE TITLE
SSL cipher suites in YAT

### ISSUE THREAD

**Issue by OlegKashtanov** [yandex/yandex-tank#144]
HI!
Can I set cipher suite for SSL?
What is default cipher suite in phantom\YAT?

**Comment by direvius** [comment]
@nnugumanov you've added an option for this didn't you?

**Comment by nnugumanov** [comment]
Yes, i did.
Options for setting cipher suite are described in readthedocs, in phatom module section.
Default suite contains all ciphers that are available for openssl installed on yat's server
