### ISSUE TITLE
422 http response show as 71 Protocol error

### ISSUE THREAD

**Issue by ant-hill** [yandex/yandex-tank#176]
our rest service use for validation exception 422 code, but when we try use yandex-tank for load testing we show response in cli as  71 Protocol error.
when we change status code to other (for ex 200) all ok

And in phout_*.log we see
1445969781.301	#0	25897	79	24	25611	183	25615	97	765	71	0
1445969782.301	#1	6642	67	13	6456	106	6456	97	765	71	0
1445969783.301	#2	6812	82	24	6595	111	6596	97	765	71	0

how we can show proper status code in our load test?

load.ini
[tank]
artifacts_base_dir=../../../trash/
[phantom]
address=127.0.0.1
port=80 ;target's port
rps_schedule=step(1,5,1,3m) ;load scheme
ammofile=ammo.txt

ammo.txt
89
GET /api/accounts HTTP/1.1
User-agent: Tank
Accept: application/json
Host: ololo-pew-pew

**Comment by nnugumanov** [comment]
that's weird, Could you please provide pcap  for one tank's request? It seems as tank really got 71 net error

**Comment by netortik** [comment]
Just tested this. Seems like http422 answer of your web server is malformed. That's why you got 71 net error.

1446127863.945          196     68      21      44      63      51      18      154     0       422
1446127864.945          311     82      22      153     54      156     18      154     0       422
1446127865.945          335     84      23      173     55      177     18      154     0       422
1446127866.945          273     87      22      120     44      124     18      154     0       422
1446127867.945          309     90      23      136     60      141     18      154     0       422
1446127868.945          223     80      17      87      39      89      18      154     0       422

**Comment by ant-hill** [comment]
@nnugumanov http://www.megafileupload.com/mb3U/my.pcap

@netortik: 
```

curl -vvv -HGET http://ololo-pew-pew/api/accounts -H 'Accept: application/json' -H 'User-agent: Tank' 
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to ololo-pew-pew (127.0.0.1) port 80 (#0)
> GET /api/accounts HTTP/1.1
> Host: ololo-pew-pew
> Accept: application/json
> User-agent: Tank
> 
< HTTP/1.1 422
* Server nginx/1.4.6 (Ubuntu) is not blacklisted
< Server: nginx/1.4.6 (Ubuntu)
< Content-Type: application/json
< Connection: close
< Vary: Accept-Encoding
< X-Powered-By: HHVM/3.10.1
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, POST, OPTIONS
< Cache-Control: no-cache
< Date: Thu, 29 Oct 2015 17:16:12 GMT
< 
* Closing connection 0
{"error":{"code":42222,"message":"Your are not allowed to perform current action"},"ruid":"5632545c34ce1"}
```

**Comment by direvius** [comment]
As stated in [rfc2616](https://www.ietf.org/rfc/rfc2616.txt):
```
6.1 Status-Line

   The first line of a Response message is the Status-Line, consisting
   of the protocol version followed by a numeric status code and its
   associated textual phrase, with each element separated by SP
   characters. No CR or LF is allowed except in the final CRLF sequence.

       Status-Line = HTTP-Version SP Status-Code SP Reason-Phrase CRLF
```
There was no SP and Reason-Phrase in your server's response.

**Comment by ant-hill** [comment]
@direvius why when my server response status code differ from 422, all works as expected?
```
curl -vvv -HGET http://ololo-pew-pew/api/accounts -H 'Accept: application/json' -H 'User-agent: Tank' 
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to ololo-pew-pew (127.0.0.1) port 80 (#0)
> GET /api/accounts HTTP/1.1
> Host: ololo-pew-pew
> Accept: application/json
> User-agent: Tank
> 
< HTTP/1.1 502 Bad Gateway
* Server nginx/1.4.6 (Ubuntu) is not blacklisted
< Server: nginx/1.4.6 (Ubuntu)
< Content-Type: application/json
< Connection: close
< Vary: Accept-Encoding
< X-Powered-By: HHVM/3.10.1
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, POST, OPTIONS
< Cache-Control: no-cache
< Date: Fri, 30 Oct 2015 09:08:22 GMT
< 
* Closing connection 0
{"error":{"code":50222,"message":"Your are not allowed to perform current action"},"ruid":"56333386cee51"}
```

```
1446195763.366	#0	19303	90	28	19122	63	19121	95	409	0	502
```
pcap file http://rghost.net/8TqDrH7wK 

if i was received corrupted response, i expected that all response marked as network error

**Comment by nnugumanov** [comment]
RFC:
The first line of a Response message is the Status-Line
...
Status-Line = HTTP-Version SP Status-Code SP Reason-Phrase CRLF
 ..

And you have "HTTP/1.1 422" which is only "HTTP-Version SP Status-Code CRLF"
So, basically, you just need to add delimiter and something as a Reason-Phrase

**Comment by ant-hill** [comment]
@nnugumanov sorry, i can not pay attention on difference between normal and malformed HTTP/1.1 string.
thank for help, seems like its a hhvm bug.
