### ISSUE TITLE
Can't install from repository on Ubuntu Trusty

### ISSUE THREAD

**Issue by ulrith** [yandex/yandex-tank#202]
I'm trying to install the software using [docs](http://yandextank.readthedocs.org/en/latest/install.html#installation-deb-packages) but getting the error:

```
The following packages have unmet dependencies:
 yandex-tank : Depends: python-requests (>= 2.5.1) but 2.2.1-1ubuntu0.3 is to be installed
E: Unable to correct problems, you have held broken packages.

```

**Comment by netortik** [comment]
It looks like a common problem - there is no debian package for python-requests=2.5.1 for precise/trusty and even vivid.
https://launchpad.net/ubuntu/precise/+package/python-requests
https://launchpad.net/ubuntu/trusty/armhf/python-requests
https://launchpad.net/ubuntu/vivid/+package/python-requests

**Comment by ulrith** [comment]
If so, why do you provide repository package for Ubuntu 14.04 LTS and recommend to use in in the manual if it just doesn’t work?...

**Comment by ulrith** [comment]
This does not work for phantom also (Ubuntu Wily):

```
W: Failed to fetch http://ppa.launchpad.net/yandex-load/main/ubuntu/dists/wily/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/yandex-load/main/ubuntu/dists/wily/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
```
So this from the manual is just completely wrong:

_Remember that if you want to use phantom as a load generator you should install it separately. **On Ubuntu you can do that by adding our PPA and installing phantom and phantom-ssl packages.** On other distros you will maybe need to build it from sources.

**Comment by direvius** [comment]
I've made a package for requests in our PPA: https://launchpad.net/~yandex-load/+archive/ubuntu/main/+build/9718400
I think it should work now.

**Comment by astopy** [comment]
Cool, that works for me.
