### ISSUE TITLE
How to get html report as shown in readme?

### ISSUE THREAD

**Issue by NielsH** [yandex/yandex-tank#216]
Hello,

I'm unable to find how I can get an html report as shown on the screenshot in the readme:
https://raw.githubusercontent.com/yandex/yandex-tank/master/logos/screen.png

I do get a logs directory, but there's no HTML file in there. The only thing I could find was this:https://github.com/yandex-load/yatank-online

Now I do get a html file in the logs directory but it looks very different, like this:
https://i.imgur.com/BINEvV9.png

I start yandex with the command `yandex-tank` and I have a load.ini file in my current directory : 
```
[tank]
plugin_web=yatank_OnlineReport

[phantom]
address=x.x.x.x
port=443
rps_schedule=line(1, 100, 1m)
ssl=1
header_http = 1.1
headers = [Host: www.example.com]
  [Connection: close]
uris = /
  /test
  /test2
```

**Comment by direvius** [comment]
The screenshot is made with old version of that plugin, it had different color scheme and different charting library. The plugin you've found is the right one. Do you think old one is better? Why?

**Comment by NielsH** [comment]
Thanks for the clarification. I had used yandex in the past and it had the other charting library - I was just so confused why it was different now, heh.

Information wise I think it shows the same, Subjectively I do think the old graphs were prettier, but the new ones are fine for me as well.
Feature wise I believe the old one did allow you to zoom in a specific timeframe which can be useful for tests with a long duration to match timestamps. The new one doesn't seem to have that option.

Feel free to close as it's not a major issue now that I know why the html output looks different.
