### ISSUE TITLE
I can`t install yandex-tank on ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by nigthmare17931** [yandex/yandex-tank#260]
I read many any guids, but was i shut without tank  i see these text in terminal:

user1@VMubuntu:$ yandex-tank /home/user1/Документы/dir/load.ini
14:54:42 [WARNING] /etc/yandex-tank is not accessible to get configs list
14:54:42 [INFO] Loading configs...
14:54:42 [INFO] Loading plugins...
14:54:42 [WARNING] Deprecated plugin classname: <module 'yandextank.plugins.ResourceCheck' from '/usr/local/lib/python2.7/dist-packages/yandextank/plugins/ResourceCheck/__init__.pyc'>. Should be 'Plugin'
14:54:42 [WARNING] Deprecated plugin classname: <module 'yandextank.plugins.ShellExec' from '/usr/local/lib/python2.7/dist-packages/yandextank/plugins/ShellExec/__init__.pyc'>. Should be 'Plugin'
14:54:42 [WARNING] Deprecated plugin classname: <module 'yandextank.plugins.Phantom' from '/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/__init__.pyc'>. Should be 'Plugin'
14:54:42 [WARNING] Deprecated plugin classname: <module 'yandextank.plugins.Aggregator' from '/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Aggregator/__init__.pyc'>. Should be 'Plugin'
14:54:42 [WARNING] Deprecated plugin classname: <module 'yandextank.plugins.Autostop' from '/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Autostop/__init__.pyc'>. Should be 'Plugin'
14:54:42 [WARNING] Deprecated plugin classname: <module 'yandextank.plugins.Monitoring' from '/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Monitoring/__init__.pyc'>. Should be 'Plugin'
14:54:42 [WARNING] Deprecated plugin classname: <module 'yandextank.plugins.Console' from '/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Console/__init__.pyc'>. Should be 'Plugin'
14:54:42 [WARNING] Deprecated plugin classname: <module 'yandextank.plugins.TipsAndTricks' from '/usr/local/lib/python2.7/dist-packages/yandextank/plugins/TipsAndTricks/__init__.pyc'>. Should be 'Plugin'
14:54:42 [WARNING] Deprecated plugin classname: <module 'yandextank.plugins.RCAssert' from '/usr/local/lib/python2.7/dist-packages/yandextank/plugins/RCAssert/__init__.pyc'>. Should be 'Plugin'
14:54:42 [INFO] Performing test
14:54:42 [INFO] Configuring plugins...
14:54:42 [WARNING] Failed TCP connection test using [127.0.0.1]:80
14:54:42 [WARNING] Failed TCP connection test using [127.0.0.1]:80
14:54:42 [WARNING] Failed TCP connection test using [127.0.0.1]:80
14:54:42 [INFO] Exception: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 261, in perform_test
    self.core.plugins_configure()
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 133, in plugins_configure
    plugin.configure()
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 92, in configure
    self.phantom.read_config()
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 96, in read_config
    stream.read_config()
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 265, in read_config
    self.address, do_test_connect, explicit_port)
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 428, in resolve
    raise RuntimeError(msg % address_str)
RuntimeError: All connection attempts failed for 127.0.0.1, use phantom.connection_test=0 to disable it

14:54:42 [ERROR] All connection attempts failed for 127.0.0.1, use phantom.connection_test=0 to disable it
14:54:42 [INFO] Trying to shutdown gracefully...
14:54:42 [INFO] Finishing test...
14:54:42 [ERROR] Failed finishing plugin <yandextank.plugins.Aggregator.plugin.AggregatorPlugin object at 0x7f1c83f8ddd0>: 'AggregatorPlugin' object has no attribute 'drain'
14:54:42 [INFO] Finishing monitoring
14:54:42 [INFO] Post-processing test...
14:54:42 [INFO] Artifacts dir: logs/2016-08-22_14-54-42.9UOmX_
14:54:42 [INFO] Done graceful shutdown
14:54:42 [INFO] Close allocated resources...
14:54:42 [INFO] Done performing test with code 1

What can I do from these? I want use yandex-tank...

P.S. Russian version:
Установил яндекс танк в соответствии со всеми гайдами, но всё равно когда я стреляю из танка в терминале сыпятся ошибки. Всё перепробовал, что можно сделать чтобы починить танк? Мне необходимо просто из него пострелять.

**Comment by direvius** [comment]
Вы пытаетесь стрелять в локалхост, на котором не запущено никаких сервисов. Танк это обнаруживает и стрелять отказывается.

**Comment by nigthmare17931** [comment]
direvius,
ну хорошо, исправил.
А теперь в чём беда?



user1@VMubuntu:~$ yandex-tank /home/user1/Документы/dir/load.ini
15:52:00 [WARNING] Lock file present: /var/lock/lunapark_9lxpwk.lock
15:52:00 [WARNING] /etc/yandex-tank is not accessible to get configs list
15:52:00 [INFO] Loading configs...
15:52:00 [INFO] Loading plugins...
15:52:00 [WARNING] Deprecated plugin classname: <module 'yandextank.plugins.ResourceCheck' from '/usr/local/lib/python2.7/dist-packages/yandextank/plugins/ResourceCheck/__init__.pyc'>. Should be 'Plugin'
15:52:00 [WARNING] Deprecated plugin classname: <module 'yandextank.plugins.ShellExec' from '/usr/local/lib/python2.7/dist-packages/yandextank/plugins/ShellExec/__init__.pyc'>. Should be 'Plugin'
15:52:00 [WARNING] Deprecated plugin classname: <module 'yandextank.plugins.Phantom' from '/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/__init__.pyc'>. Should be 'Plugin'
15:52:00 [WARNING] Deprecated plugin classname: <module 'yandextank.plugins.Aggregator' from '/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Aggregator/__init__.pyc'>. Should be 'Plugin'
15:52:00 [WARNING] Deprecated plugin classname: <module 'yandextank.plugins.Autostop' from '/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Autostop/__init__.pyc'>. Should be 'Plugin'
15:52:00 [WARNING] Deprecated plugin classname: <module 'yandextank.plugins.Monitoring' from '/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Monitoring/__init__.pyc'>. Should be 'Plugin'
15:52:00 [WARNING] Deprecated plugin classname: <module 'yandextank.plugins.Console' from '/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Console/__init__.pyc'>. Should be 'Plugin'
15:52:00 [WARNING] Deprecated plugin classname: <module 'yandextank.plugins.TipsAndTricks' from '/usr/local/lib/python2.7/dist-packages/yandextank/plugins/TipsAndTricks/__init__.pyc'>. Should be 'Plugin'
15:52:00 [WARNING] Deprecated plugin classname: <module 'yandextank.plugins.RCAssert' from '/usr/local/lib/python2.7/dist-packages/yandextank/plugins/RCAssert/__init__.pyc'>. Should be 'Plugin'
15:52:00 [INFO] Performing test
15:52:00 [INFO] Configuring plugins...
15:52:00 [INFO] Exception: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 261, in perform_test
    self.core.plugins_configure()
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 133, in plugins_configure
    plugin.configure()
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 92, in configure
    self.phantom.read_config()
  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 71, in read_config
    self.answ_log = self.core.mkstemp(".log", "answ_")
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 438, in mkstemp
    fd, fname = tempfile.mkstemp(suffix, prefix, directory)
  File "/usr/lib/python2.7/tempfile.py", line 314, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 13] Permission denied: 'logs/answ_g3Jqst.log'

15:52:00 [ERROR] [Errno 13] Permission denied: 'logs/answ_g3Jqst.log'
15:52:00 [INFO] Trying to shutdown gracefully...
15:52:00 [INFO] Finishing test...
15:52:00 [ERROR] Failed finishing plugin <yandextank.plugins.Aggregator.plugin.AggregatorPlugin object at 0x7fc3e6670e50>: 'AggregatorPlugin' object has no attribute 'drain'
15:52:00 [INFO] Finishing monitoring
15:52:00 [INFO] Post-processing test...
15:52:00 [INFO] Close allocated resources...
15:52:00 [ERROR] Exception: [Errno 13] Permission denied: 'logs/2016-08-22_15-52-00.V23e6X'

**Comment by netortik** [comment]
Теперь он не может записать логи, потому что вы его запускаете из корня от пользователя, у которого нет на эту директорию прав. Запускайте у себя из /home/%username%.

**Comment by nigthmare17931** [comment]
Но так это корнем и является

**Comment by nigthmare17931** [comment]
Вообще, есть ли чёткая последовательность команд, которая приведёт к успеху и будет установлен этот злой яндекс танк? Кому не сложно можете поделится? 

https://docs.docker.com/engine/installation/linux/ubuntulinux/
http://yandextank.readthedocs.io/en/latest/install.html
То что выше не помогло ваще ниразу

**Comment by direvius** [comment]
@nigthmare17931 читайте сообщения в логах, там все написанно.

**Comment by nigthmare17931** [comment]
https://github.com/[direvius](url) спасибо за дельные советы.
Так вопрос и остался без ответа

**Comment by direvius** [comment]
@nigthmare17931 какой вариант инсталляции из документации вы использовали? Танк у вас успешно запускается (т.е. вы его поставили), проблема в доступах к файловой системе.

**Comment by KlonD90** [comment]
Проблема в том что документация не описывает сейчас как из докера стрелять какие параметры передавать и т.д.

**Comment by direvius** [comment]
@KlonD90 [вот](http://yandextank.readthedocs.io/en/latest/install.html#docker-container) же.

**Comment by KlonD90** [comment]
ну нет ._. я вечерком уж пришлю побольше буковок
