### ISSUE TITLE
Deprecated plugin classname [Warning]

### ISSUE THREAD

**Issue by doctornkz** [yandex/yandex-tank#263]
@DenMikov Приветствую! При запуске танка в консоли фигурируют сообщения типа [WARNING] Deprecated plugin classname: <module 'yandextank.plugins.ShellExec' from '/usr/local/lib/python2.7/dist-packages/yandextank/plugins/ShellExec/__init__.pyc'>. Should be 'Plugin' . Как от них избавиться?

**Comment by netortik** [comment]
Нужно обновлять все плагины на стороне танка.

Надо спрятать эти ворнинги в дебаг, чтобы не смущать пользователей.

25 авг. 2016 г. 11:17 AM пользователь "Oles Pisarenko" <
notifications@github.com> написал:

**Comment by doctornkz** [comment]
Подразумевается, что, если танк в докере, то там все ванильное и обновленное. Можно и спрятать, посмотрим, что @direvius скажет.

**Comment by netortik** [comment]
Не пользователям обновлять.
Мейнтейнерам плагинов, которые используются.

Этот ворнинг говорит, что плагин архитектурно устарел и неплохо бы его
порефакторить и обновить.

25 авг. 2016 г. 11:22 AM пользователь "Oles Pisarenko" <
notifications@github.com> написал:

**Comment by doctornkz** [comment]
Я понимаю, потому и завел тикет, чтобы мы это починили или спрятали на своей стороне.

**Comment by direvius** [comment]
Починили.
