### ISSUE TITLE
possible bug in aggregator

### ISSUE THREAD

**Issue by doctornkz** [yandex/yandex-tank#27]
[phantom]
address= example.org
rps_schedule = const(1, 10).
uris = /
    /buy
headers = [Host: mts-maps.yandex.ru]
    [Connection: close]
writelog = 1

You can see this after test in console:

       HTTP for 1 RPS:                     
         2  28.57%: 200 OK                 
         3  42.86%: 302 Found              
         2  28.57%: 502 Bad Gateway        
                                           
        NET for 1 RPS:                     
         7 100.00%: 0 Success              

7(Seven) good responses and 0 bad responses.
                                           
But we have 10 requests in answ log:

$ cat answ_icvgDw.log  | grep GET | wc -l
10

and 10 good net responses
<pre>
$ cat answ_icvgDw.log  | grep -B 1 GET 
63 323 13379 12913 0
GET / HTTP/1.0
--
66 359 699 590 0
GET /buy HTTP/1.0
--
63 20295 564384 564220 0
GET / HTTP/1.0
--
66 359 751 647 0
GET /buy HTTP/1.0
--
63 323 12229 12130 0
GET / HTTP/1.0
--
66 359 815 709 0
GET /buy HTTP/1.0
--
63 20294 563137 562956 0
GET / HTTP/1.0
--
66 359 746 638 0
GET /buy HTTP/1.0
--
63 323 12230 12144 0
GET / HTTP/1.0
--
66 359 706 601 0
GET /buy HTTP/1.0
</pre>

**Comment by direvius** [comment]
New aggregator was written from scratch.
