### ISSUE TITLE
Невозможно установить

### ISSUE THREAD

**Issue by des1roer** [yandex/yandex-tank#488]
➜   sudo apt-get install python-software-properties
[sudo] пароль для zuev_np: 
Попробуйте ещё раз.
[sudo] пароль для zuev_np: 
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Некоторые пакеты невозможно установить. Возможно, вы просите невозможного,
или же используете нестабильную версию дистрибутива, где запрошенные вами
пакеты ещё не созданы или были удалены из Incoming.
Следующая информация, возможно, поможет вам:

Пакеты, имеющие неудовлетворённые зависимости:
 python-software-properties : Зависит: python-apt (>= 0.6.20ubuntu16) но он не может быть установлен
                              Зависит: python-pycurl но он не может быть установлен
E: Невозможно исправить ошибки, у вас отложены (held) битые пакеты.

**Comment by nettorta** [comment]
Здравствуйте.
Мы не поддерживаем установку через deb пакеты, она работает не везде и постоянно по-разному ломается. Об этом написано в документации.
Используйте pip или, если по каким-то причинам питонячая дистрибуция не подходит или не работает, docker.

**Comment by direvius** [comment]
Кроме того, **python-software-properties** -- это вообще не мы.
