### ISSUE TITLE
Нет yandex-tank-jmeter в docker hub

### ISSUE THREAD

**Issue by dubrovin** [yandex/yandex-tank#491]
При запуске по документации http://yandextank.readthedocs.io/en/latest/install.html
```
docker run \
    -v $(pwd):/var/loadtest \
    -v $SSH_AUTH_SOCK:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent \
    --net host \
    -it direvius/yandex-tank-jmeter
```
Получаю ошибку:
`docker: Error response from daemon: pull access denied for direvius/yandex-tank-jmeter, repository does not exist or may require 'docker login'.`

В docker залогиненный. Поиск по докер хабу, тоже не дал результатов.

**Comment by sgaynetdinov** [comment]
@dubrovin так в документации написан `direvius/yandex-tank`, откуда `direvius/yandex-tank-jmeter`

**Comment by sorrowless** [comment]
@sgaynetdinov нет, там прямо в первом предложении документации написано, что если нужен jmeter, то надо тянуть контейнер с jmeter-ом:

> Install docker and use direvius/yandex-tank (or, if you need jmeter, try direvius/yandex-tank-jmeter

я с такой же проблемой столкнулся.

**Comment by sibilkov** [comment]
Судя по всему этого образа больше нет. Я качал мастер ветку этого репозитория, там есть Dockerfile.jmeter и после пары правок (верся жиметра для скачивания криво передается) он даже запускается и создает образ, только тот всё равно не работает, контейнер падает с сообщением [ERROR] Exception: No module named JMeter (как и все остальные варианты установки последней версии).

**Comment by ivang7** [comment]
Почти полгода прошло, будет официальная версия яндекс танка в докере с jmeter? Нашел кто-нибудь рабочие образы в других репозиториях?

**Comment by sibilkov** [comment]
> Почти полгода прошло, будет официальная версия яндекс танка в докере с jmeter? Нашел кто-нибудь рабочие образы в других репозиториях?
Я на той неделе собирал образ из Dockerfile.jmeter из репозитория и у меня всё отработало (не совсем гладко, точно не помню) но в итоге я смог и не заморочился.

**Comment by direvius** [comment]
собрал direvius/yandex-tank:jmeter. Можно пробовать.

**Comment by ivang7** [comment]
отлично, работает.
Только в /usr/local/lib/python2.7/dist-packages/yandextank/core/config/00-base.yaml нужно заменить 
jmeter:
  enabled: false
  package: JMeter
*на*
jmeter:
  enabled: false
  package: yandextank.plugins.JMeter

**Comment by sgaynetdinov** [comment]
@dubrovin можем закрыть ?

**Comment by dubrovin** [comment]
> @dubrovin можно закрыть ?

Да, спасибо :)
