### ISSUE TITLE
Docker image failing to start

### ISSUE THREAD

**Issue by vveliev** [yandex/yandex-tank#523]
```docker commit fd4835a767a4 my-broken-container &&
docker run -it my-broken-container /bin/bash
sha256:b38540dd61b07c5b556233dfe8a9c5c107fcc7bf487aa5e2e20ed9a9ce7ef0df
03:29:28 [INFO] Converted config:
core: {}

03:29:28 [WARNING] /etc/yandex-tank is not accessible to get configs list
03:29:28 [ERROR] Exception: Validation error:
phantom:
  address: [required field]
  load_profile: [required field]```

**Comment by nettorta** [comment]
Do you pass tank config file into container?

**Comment by vveliev** [comment]
No, I don't think documentation have it as requirements

**Comment by nettorta** [comment]
Create config file for tank, e.g. using tutorial, http://yandextank.readthedocs.io/en/latest/tutorial.html .
And pass it to yandex-tank as we mentioned in 'installation' section of documentation: http://yandextank.readthedocs.io/en/latest/install.html#docker-container

**Comment by vveliev** [comment]
Thanks!
