### ISSUE TITLE
Зависимость от непонятного yasmapi

### ISSUE THREAD

**Issue by evgkrsk** [yandex/yandex-tank#622]
Ищу по всему интернету - yasmapi взять просто негде. Похоже, он есть только на не отвечающем наружу https://pypi.yandex-team.ru/simple

**Comment by nettorta** [comment]
@evgkrsk Расскажите подробнее, где эта зависимость? По поиску нашёл только добавленную (и уже  удалённую) в Dockerfile? Может, я что-то не нашёл. Починим asap

**Comment by fomars** [comment]
Падает при установке или при запуске? Есть лог?

**Comment by evgkrsk** [comment]
В крайнем релизе (1.10.0 на тот момент, сейчас уже и в 1.10.1):
```
evg@thinkpad ~/git/yandex-tank $git checkout v1.10.1
HEAD is now at bb4dfb2... Merge pull request #621 from yandex/release
evg@thinkpad ~/git/yandex-tank $git grep -i yasmapi 
yandextank/plugins/YASM/plugin.py:from yasmapi import RtGolovanRequest
yandextank/plugins/YASM/plugin.py:    :type yasmapi_cfg: Panel
yandextank/plugins/YASM/plugin.py:            yasmapi_cfg = {}
yandextank/plugins/YASM/plugin.py:                yasmapi_cfg.setdefault(panel.host, {})[panel.tags] = panel.signals
yandextank/plugins/YASM/plugin.py:            logger.info('yasmapi cfg: {}'.format(yasmapi_cfg))
yandextank/plugins/YASM/plugin.py:            self._as_dict = yasmapi_cfg
yandextank/plugins/YASM/plugin.py:    def __init__(self, yasm_cfg, yasmapi_timeout):
yandextank/plugins/YASM/plugin.py:        self.timeout = yasmapi_timeout
```

**Comment by evgkrsk** [comment]
Падает при установке т.к. ни в каком репо нет такого модуля. При запуске плагина YASM будет трейсбэк. Лога нет, т.к. мой пакетный менеджер уже на подходе не пропускает такое устанавливать. Я хотел было собрать нужный модуль питона, но нет.

**Comment by fomars** [comment]
Плагин YASM по умолчанию отключен, в setup.py зависимости от него нет. Как
вы устанавливаете танк?

пт, 13 июл. 2018 г., 10:52 Evgenii Terechkov <notifications@github.com>:

**Comment by fomars** [comment]
Попробуйте ставить танк через pip:
`pip install git+https://github.com/yandex/yandex-tank.git`

**Comment by evgkrsk** [comment]
То что плагин по умолчанию выключен не отменяет того, что модуля yasmapi нет в открытом доступе.

Система сборки у нас генерирует зависимости на то что реально есть в коде.

**Comment by direvius** [comment]
@evgkrsk не нужно ставить то, чего нет в setup.py.

**Comment by fomars** [comment]
Можете попробовать один из следующих способов обхода:
- Удалять папку YASM после клонирования репозитория
- Подложить пустой модуль yasmapi
- Попатчить систему сборки чтоб она работала по стандартам setuptools

**Comment by fomars** [comment]
Убрали в 1.10.3
