### ISSUE TITLE
Overload service is unavailable

### ISSUE THREAD

**Issue by NanoBjorn** [yandex/yandex-tank#905]
https://overload.yandex.net/ is unavailable, is this expected and we should not rely on it anymore?

**Comment by ligreen** [comment]
Sorry, we had technical problems. We have already fixed them.

By the way, did you know that we have launched the yandex cloud loadtesting service: https://cloud.yandex.ru/en/docs/load-testing/ . 
Have you tried it yet?

**Comment by NanoBjorn** [comment]
Can I post reports from tank to this new service btw? Would pretty useful if Overload is going to be turned off eventually

**Comment by ligreen** [comment]
> Can I post reports from tank to this new service btw? Would pretty useful if Overload is going to be turned off eventually

Yes, you can post reports from tank to this new service. You need to register the tank as an external agent in the service: https://cloud.yandex.ru/en/docs/load-testing/tutorials/loadtesting-external-agent

Also, you could migrate all your reporst from Overload into Loadtesting: https://cloud.yandex.ru/en/docs/load-testing/tutorials/loadtesting-overload-migration
